type ProblemSeed = {
  id: string
  theme_id: string
  themeName: string
  title: string
  level: number
  type: string
  statement: string
  requirements?: string
  hint: string
  answer: string
  explanation: string
  common_mistakes: string
}

const dockerProblem = (problem: ProblemSeed): ProblemSeed => problem

export const DOCKER_PROBLEM_SEEDS: ProblemSeed[] = [
  dockerProblem({ id: 'local-docker-001', theme_id: 'local-docker-basic', themeName: 'Docker: 基礎', title: 'Docker の役割を説明する', level: 1, type: 'concept', statement: 'Docker は何のために使うのかを、初学者向けに 2 点で説明してください。', requirements: '環境差分を減らすことと、アプリ実行単位をまとめることに触れてください。', hint: '「同じ環境で動かす」と「まとめて配る」の 2 観点で考えると整理しやすいです。', answer: '1. Docker はアプリを動かすのに必要な環境をまとめて扱えるので、開発者ごとの環境差分を減らせます。\n2. アプリと必要な設定をコンテナとしてまとめて実行・配布しやすくなります。', explanation: 'Docker の価値は、再現性の高い実行環境を作れる点にあります。', common_mistakes: '仮想マシンそのものと完全に同じと考えると役割を説明しにくくなります。' }),
  dockerProblem({ id: 'local-docker-002', theme_id: 'local-docker-basic', themeName: 'Docker: 基礎', title: 'Docker が使えるか確認する手順を書く', level: 1, type: 'procedure', statement: '自分の PC で Docker が使えるか確認したいです。基本確認手順を 2 ステップで書いてください。', requirements: 'Docker Desktop などの起動確認と、コマンド確認に触れてください。', hint: 'アプリ起動確認のあと、ターミナルでバージョン確認をする流れです。', answer: '1. Docker Desktop などの Docker 本体が起動しているか確認する。\n2. ターミナルで `docker --version` を実行してコマンドが使えるか確認する。', explanation: 'GUI 側が起動していてもコマンドが使えないことがあるため、両方確認すると安全です。', common_mistakes: '`docker compose` だけ試して本体起動確認を省くと、原因切り分けがしづらくなります。' }),
  dockerProblem({ id: 'local-docker-003', theme_id: 'local-docker-basic', themeName: 'Docker: 基礎', title: 'イメージとコンテナの違いを説明する', level: 1, type: 'concept', statement: 'Docker イメージと Docker コンテナの違いを、それぞれ 1 文ずつで説明してください。', requirements: 'イメージは設計図、コンテナは実行中の実体という意味が伝わるように書いてください。', hint: '「元になるもの」と「実際に動くもの」を分けると整理しやすいです。', answer: 'イメージはコンテナを作る元になる設計図です。\nコンテナはそのイメージから作られて実際に動いている実行単位です。', explanation: 'この違いを理解すると、build と run の役割も見えやすくなります。', common_mistakes: '両方を同じものとして説明すると、操作コマンドの意味が分かりにくくなります。' }),
  dockerProblem({ id: 'local-docker-004', theme_id: 'local-docker-basic', themeName: 'Docker: 基礎', title: 'アプリを Docker で動かす基本流れを書く', level: 2, type: 'procedure', statement: 'アプリを Docker で動かすときの基本流れを 3 ステップで書いてください。', requirements: 'Dockerfile、build、run の流れを含めてください。', hint: '設計図を書く → イメージを作る → コンテナを起動する、の順です。', answer: '1. まず Dockerfile を用意して、アプリの実行方法を定義する。\n2. `docker build` でイメージを作成する。\n3. `docker run` でコンテナを起動してアプリを動かす。', explanation: 'Docker 利用の最小単位は Dockerfile、build、run の 3 段階です。', common_mistakes: 'Dockerfile を作らずにいきなり run しようとすると、独自アプリの実行条件が定まりません。' }),
  dockerProblem({ id: 'local-docker-005', theme_id: 'local-docker-basic', themeName: 'Docker: 基礎', title: 'Docker を使う利点を説明する', level: 1, type: 'concept', statement: 'Docker を研修や実務で使う利点を 2 点書いてください。', requirements: '開発環境の統一と配布・再現のしやすさに触れてください。', hint: 'チーム開発で困ることを想像すると書きやすいです。', answer: '1. 開発者ごとの環境差分を減らして、同じ条件でアプリを動かしやすくなる。\n2. アプリの実行環境ごとまとめて再現・配布しやすくなる。', explanation: '環境差分と再現性は Docker 導入理由として非常に多いです。', common_mistakes: '単に「便利」と書くだけでは、何が便利なのかが伝わりません。' }),
  dockerProblem({ id: 'local-docker-006', theme_id: 'local-docker-dockerfile', themeName: 'Docker: Dockerfile', title: 'Node アプリの Dockerfile を書く', level: 2, type: 'procedure', statement: 'Node.js アプリをコンテナで動かしたいです。ベースイメージに `node:20-alpine` を使い、作業ディレクトリを `/app` にし、`package.json` をコピーして `npm install` 後、全体をコピーして `npm start` で起動する Dockerfile を書いてください。', requirements: '`FROM`, `WORKDIR`, `COPY`, `RUN`, `CMD` を含めてください。', hint: '依存関係インストール前に package.json をコピーします。', answer: 'FROM node:20-alpine\nWORKDIR /app\nCOPY package.json ./\nRUN npm install\nCOPY . .\nCMD ["npm", "start"]', explanation: 'Node アプリの最小 Dockerfile としてよく使う構成です。', common_mistakes: '最初に全ファイルを COPY すると、依存関係キャッシュが効きにくくなります。' }),
  dockerProblem({ id: 'local-docker-007', theme_id: 'local-docker-dockerfile', themeName: 'Docker: Dockerfile', title: 'FROM の役割を説明する', level: 1, type: 'concept', statement: 'Dockerfile の `FROM` は何を指定するのかを 1 文で説明してください。', requirements: 'ベースイメージを選ぶことが伝わるように書いてください。', hint: 'コンテナの土台になるものです。', answer: '`FROM` は、その Dockerfile がどのベースイメージを土台にして作られるかを指定します。', explanation: 'ベースイメージが変わると、使える OS やランタイムも変わります。', common_mistakes: 'アプリ名を書く場所だと考えると Dockerfile の構成を誤解しやすくなります。' }),
  dockerProblem({ id: 'local-docker-008', theme_id: 'local-docker-dockerfile', themeName: 'Docker: Dockerfile', title: 'COPY の役割を説明する', level: 1, type: 'concept', statement: 'Dockerfile の `COPY . .` は何をしているのかを 1 文で説明してください。', requirements: 'ローカルのファイルをイメージ内へコピーすることに触れてください。', hint: '手元のファイルをコンテナ側へ持っていく命令です。', answer: '`COPY . .` は、ビルド元ディレクトリのファイルをイメージ内の現在ディレクトリへコピーします。', explanation: 'アプリ本体のソースコードをイメージへ入れるためによく使います。', common_mistakes: 'ホスト PC とコンテナが自動で同じファイルを共有するわけではありません。' }),
  dockerProblem({ id: 'local-docker-009', theme_id: 'local-docker-dockerfile', themeName: 'Docker: Dockerfile', title: '3000 番ポートで起動する Dockerfile を書く', level: 2, type: 'procedure', statement: 'Node.js アプリを 3000 番ポートで動かす Dockerfile の一部として、`EXPOSE` と `CMD` を含む最小コードを書いてください。起動コマンドは `npm start` です。', requirements: '`EXPOSE 3000` と `CMD ["npm", "start"]` を含めてください。', hint: 'ポート公開の宣言と起動コマンドが必要です。', answer: 'EXPOSE 3000\nCMD ["npm", "start"]', explanation: '`EXPOSE` は利用ポートの宣言、`CMD` は起動時の既定コマンドです。', common_mistakes: '`RUN npm start` にするとビルド時に実行されてしまいます。' }),
  dockerProblem({ id: 'local-docker-010', theme_id: 'local-docker-dockerfile', themeName: 'Docker: Dockerfile', title: 'package.json を先にコピーする理由を説明する', level: 2, type: 'concept', statement: 'Dockerfile で `package.json` だけ先に `COPY` してから `npm install` することが多い理由を 1 点説明してください。', requirements: 'ビルドキャッシュに触れてください。', hint: '依存関係に変化がないとき、毎回 install をやり直さなくて済みます。', answer: '依存関係ファイルが変わっていなければ `npm install` のレイヤーをキャッシュ再利用できるため、ビルドを速くしやすいからです。', explanation: 'Dockerfile の順番はビルド速度に影響します。', common_mistakes: '単に「決まりだから」と覚えると応用が利きにくくなります。' }),
  dockerProblem({ id: 'local-docker-011', theme_id: 'local-docker-image', themeName: 'Docker: イメージ操作', title: 'イメージを build するコマンドを書く', level: 1, type: 'procedure', statement: '現在のフォルダにある Dockerfile から、`todo-app` という名前のイメージを作りたいです。コマンドを書いてください。', requirements: 'タグは latest のままで構いません。', hint: '`-t` で名前を付けます。', answer: 'docker build -t todo-app .', explanation: '`docker build -t イメージ名 .` が基本形です。', common_mistakes: '最後の `.` を忘れるとビルドコンテキストが指定されません。' }),
  dockerProblem({ id: 'local-docker-012', theme_id: 'local-docker-image', themeName: 'Docker: イメージ操作', title: 'イメージ一覧を見るコマンドを書く', level: 1, type: 'procedure', statement: 'ローカルにある Docker イメージ一覧を確認したいです。コマンドを書いてください。', hint: 'images という単語を使います。', answer: 'docker images', explanation: '`docker images` でローカルのイメージ一覧を確認できます。', common_mistakes: '`docker ps` はコンテナ一覧です。' }),
  dockerProblem({ id: 'local-docker-013', theme_id: 'local-docker-image', themeName: 'Docker: イメージ操作', title: 'イメージを削除するコマンドを書く', level: 1, type: 'procedure', statement: '`todo-app:latest` イメージを削除したいです。コマンドを書いてください。', hint: '`remove image` の短いコマンドです。', answer: 'docker rmi todo-app:latest', explanation: '`docker rmi` は不要になったイメージ削除で使います。', common_mistakes: '`docker rm` はコンテナ削除用です。' }),
  dockerProblem({ id: 'local-docker-014', theme_id: 'local-docker-image', themeName: 'Docker: イメージ操作', title: 'タグの役割を説明する', level: 1, type: 'concept', statement: 'Docker イメージのタグは何のために使うのかを 1 文で説明してください。', requirements: 'バージョンや識別に使うことが伝わるように書いてください。', hint: '`latest` や `v1` のような付け分けを思い出してください。', answer: 'タグは、同じイメージ名の中でバージョンや用途を区別して管理しやすくするために使います。', explanation: 'タグを分けると、どの版を使うかを明確にできます。', common_mistakes: 'タグをファイル名のように考えると Docker の識別構造を誤解しやすくなります。' }),
  dockerProblem({ id: 'local-docker-015', theme_id: 'local-docker-image', themeName: 'Docker: イメージ操作', title: 'イメージに別タグを付けるコマンドを書く', level: 2, type: 'procedure', statement: '`todo-app:latest` に対して `todo-app:v1` という別タグを付けたいです。コマンドを書いてください。', hint: '`docker tag 元 先` の順です。', answer: 'docker tag todo-app:latest todo-app:v1', explanation: 'tag コマンドで既存イメージへ別名を付けられます。', common_mistakes: 'build し直さなくてもタグ付けだけなら `docker tag` で十分です。' }),
  dockerProblem({ id: 'local-docker-016', theme_id: 'local-docker-container', themeName: 'Docker: コンテナ操作', title: 'バックグラウンドでコンテナ起動するコマンドを書く', level: 2, type: 'procedure', statement: '`todo-app` イメージから、名前を `todo-web`、ポートを `3000:3000` でバックグラウンド起動したいです。コマンドを書いてください。', requirements: '`-d`, `--name`, `-p` を含めてください。', hint: 'detach, name, port の 3 つが必要です。', answer: 'docker run -d --name todo-web -p 3000:3000 todo-app', explanation: 'よく使う起動オプションをまとめた実践形です。', common_mistakes: '`-p` を忘れるとホスト側からアクセスできません。' }),
  dockerProblem({ id: 'local-docker-017', theme_id: 'local-docker-container', themeName: 'Docker: コンテナ操作', title: '動いているコンテナを止めるコマンドを書く', level: 1, type: 'procedure', statement: '`todo-web` コンテナを停止したいです。コマンドを書いてください。', hint: 'stop コマンドです。', answer: 'docker stop todo-web', explanation: '起動中コンテナの停止には `docker stop` を使います。', common_mistakes: '`docker rm` は停止前のコンテナには基本的に使いません。' }),
  dockerProblem({ id: 'local-docker-018', theme_id: 'local-docker-container', themeName: 'Docker: コンテナ操作', title: 'コンテナログを見るコマンドを書く', level: 1, type: 'procedure', statement: '`todo-web` コンテナのログを確認したいです。コマンドを書いてください。', hint: 'logs コマンドを使います。', answer: 'docker logs todo-web', explanation: '起動失敗やエラー確認でまず見る基本コマンドです。', common_mistakes: 'ログ確認前にコンテナを消すと原因追跡がしづらくなります。' }),
  dockerProblem({ id: 'local-docker-019', theme_id: 'local-docker-container', themeName: 'Docker: コンテナ操作', title: 'docker exec の役割を説明する', level: 2, type: 'concept', statement: '`docker exec -it` は何のために使うのかを 1 文で説明してください。', requirements: '実行中コンテナの中でコマンドを実行することに触れてください。', hint: 'シェルに入る用途を思い出してください。', answer: '`docker exec -it` は、起動中のコンテナ内でシェルやコマンドを実行して中身を確認・操作するときに使います。', explanation: 'コンテナ内調査や一時確認でよく使います。', common_mistakes: '`docker run` と混同すると、新しいコンテナを増やしてしまいます。' }),
  dockerProblem({ id: 'local-docker-020', theme_id: 'local-docker-container', themeName: 'Docker: コンテナ操作', title: '停止済みコンテナを削除するコマンドを書く', level: 1, type: 'procedure', statement: '`todo-web` という停止済みコンテナを削除したいです。コマンドを書いてください。', hint: 'container remove の短いコマンドです。', answer: 'docker rm todo-web', explanation: '`docker rm` は不要になった停止済みコンテナの削除に使います。', common_mistakes: '動作中なら先に stop が必要なことがあります。' }),
  dockerProblem({ id: 'local-docker-021', theme_id: 'local-docker-compose', themeName: 'Docker: docker-compose', title: 'web と db を持つ compose 設定を書く', level: 3, type: 'procedure', statement: 'web サービスは `todo-app:latest` を使い `3000:3000` を公開、db サービスは `mysql:8.0` を使う最小の `docker-compose.yml` を書いてください。', requirements: '`services`, `web`, `db`, `ports`, `image` を含めてください。', hint: '最小構成でよいので、image と ports を中心に書きます。', answer: 'services:\n  web:\n    image: todo-app:latest\n    ports:\n      - "3000:3000"\n  db:\n    image: mysql:8.0', explanation: 'compose では複数サービスを 1 ファイルでまとめて管理できます。', common_mistakes: 'services の下に web / db を入れ忘れると compose の形になりません。' }),
  dockerProblem({ id: 'local-docker-022', theme_id: 'local-docker-compose', themeName: 'Docker: docker-compose', title: 'compose の service の役割を説明する', level: 2, type: 'concept', statement: '`docker-compose.yml` の `service` は何を表すのかを 1 文で説明してください。', requirements: 'アプリや DB など、1 つの実行単位を定義することが伝わるように書いてください。', hint: 'web や db のような単位です。', answer: 'service は、アプリやデータベースなど、compose で一緒に管理したいコンテナの実行単位を表します。', explanation: 'service 単位で image、ports、environment などを定義します。', common_mistakes: 'service をコンテナ 1 個の実体そのものだけと考えると、設定単位としての意味を見失いやすくなります。' }),
  dockerProblem({ id: 'local-docker-023', theme_id: 'local-docker-compose', themeName: 'Docker: docker-compose', title: 'compose でバックグラウンド起動するコマンドを書く', level: 1, type: 'procedure', statement: '`docker-compose.yml` に定義したサービス群をバックグラウンド起動したいです。コマンドを書いてください。', hint: 'up と -d を使います。', answer: 'docker compose up -d', explanation: 'compose v2 では `docker compose up -d` が基本形です。', common_mistakes: '`docker run` では複数サービスをまとめて起動できません。' }),
  dockerProblem({ id: 'local-docker-024', theme_id: 'local-docker-compose', themeName: 'Docker: docker-compose', title: 'compose でサービス群を停止・削除するコマンドを書く', level: 1, type: 'procedure', statement: '`docker-compose.yml` で起動したサービス群をまとめて停止・削除したいです。コマンドを書いてください。', hint: 'down コマンドです。', answer: 'docker compose down', explanation: '`docker compose down` は compose で起動したサービス群をまとめて片付けるときに使います。', common_mistakes: '`docker stop` だけでは複数サービスをまとめて管理しづらいです。' }),
  dockerProblem({ id: 'local-docker-025', theme_id: 'local-docker-compose', themeName: 'Docker: docker-compose', title: 'compose の ports の意味を説明する', level: 2, type: 'concept', statement: '`docker-compose.yml` の `ports: - "3000:3000"` は何を意味するのかを 1 文で説明してください。', requirements: 'ホスト側とコンテナ側のポート対応に触れてください。', hint: '左がホスト、右がコンテナです。', answer: '`ports: "3000:3000"` は、ホストの 3000 番ポートへのアクセスをコンテナの 3000 番ポートへつなぐ設定です。', explanation: 'ポート公開はブラウザや他サービスからアクセスするための基本設定です。', common_mistakes: '両方ともホスト側だと誤解すると、接続トラブルの原因になります。' }),
]
