type ProblemSeed = {
  id: string
  theme_id: string
  themeName: string
  title: string
  level: number
  type: string
  statement: string
  requirements?: string
  hint: string
  answer: string
  explanation: string
  common_mistakes: string
}

const js = (problem: ProblemSeed): ProblemSeed => problem

export const JAVASCRIPT_PROBLEM_SEEDS: ProblemSeed[] = [
  js({ id: 'local-javascript-001', theme_id: 'local-javascript-basic', themeName: 'JavaScript: 基本文法', title: '再代入しない変数宣言', level: 1, type: 'fill_blank', statement: '再代入しない変数を宣言したいです。空欄を埋めてください。\n\n__________ userName = "Aoki";', hint: 'ES6 以降でよく使う宣言です。', answer: 'const', explanation: '再代入しない値には `const` を使うのが基本です。', common_mistakes: '`let` でも動きますが、再代入しない意図は弱くなります。' }),
  js({ id: 'local-javascript-002', theme_id: 'local-javascript-basic', themeName: 'JavaScript: 基本文法', title: 'テンプレートリテラルの埋め込み記法', level: 1, type: 'fill_blank', statement: '`const name = "Aoki";` があるとき、`Hello, Aoki` を作る空欄を埋めてください。\n\n`Hello, __________`', hint: 'テンプレートリテラル内で使う `${...}` の形です。', answer: '${name}', explanation: 'テンプレートリテラルでは `${変数}` で値を埋め込めます。', common_mistakes: '`+ name` は別解ですが、この問題はテンプレートリテラル前提です。' }),
  js({ id: 'local-javascript-003', theme_id: 'local-javascript-basic', themeName: 'JavaScript: 基本文法', title: '厳密比較演算子', level: 1, type: 'fill_blank', statement: '値も型も比較したいです。空欄を埋めてください。\n\nif (count __________ 3) {', hint: '`==` より厳密な比較です。', answer: '===', explanation: 'JavaScript では通常 `===` を使うと意図しない型変換を避けやすくなります。', common_mistakes: '`==` は暗黙の型変換が入るため、研修では避けることが多いです。' }),
  js({ id: 'local-javascript-004', theme_id: 'local-javascript-basic', themeName: 'JavaScript: 基本文法', title: '1 から 3 を出力する for 文を書く', level: 1, type: 'code', statement: '1 から 3 までを `console.log` で順番に表示する `for` 文を書いてください。', requirements: '`for` を使うこと\n1, 2, 3 の順で出すこと', hint: '初期値 1、3 以下の間だけ回します。', answer: 'for (let i = 1; i <= 3; i++) {\n  console.log(i);\n}', explanation: '反復回数が決まっているときは `for` 文が基本です。', common_mistakes: '`i < 3` にすると 3 が出ません。' }),
  js({ id: 'local-javascript-005', theme_id: 'local-javascript-basic', themeName: 'JavaScript: 基本文法', title: '20 歳以上なら adult と出す if 文を書く', level: 1, type: 'code', statement: '`age` 変数が 20 以上なら `adult` と表示する `if` 文を書いてください。', requirements: '`console.log("adult")` を使うこと', hint: '比較には `>=` を使います。', answer: 'if (age >= 20) {\n  console.log("adult");\n}', explanation: '条件分岐の最小形です。', common_mistakes: '`>` にすると 20 歳ちょうどが外れてしまいます。' }),
  js({ id: 'local-javascript-006', theme_id: 'local-javascript-basic', themeName: 'JavaScript: 基本文法', title: 'name と age を持つオブジェクトを作る', level: 1, type: 'code', statement: '`name` が `Aoki`、`age` が `25` のオブジェクト `user` を作るコードを書いてください。', requirements: 'オブジェクトリテラルで書くこと', hint: '`{ key: value }` の形です。', answer: 'const user = {\n  name: "Aoki",\n  age: 25,\n};', explanation: '基本的なオブジェクト作成は研修でもよく使います。', common_mistakes: '`=` の右側を配列にしないように注意します。' }),
  js({ id: 'local-javascript-007', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: '配列の先頭要素を取る記法', level: 1, type: 'fill_blank', statement: '`const numbers = [10, 20, 30];` の先頭要素を取りたいです。空欄を埋めてください。\n\nnumbers[__________]', hint: 'JavaScript の配列は 0 から始まります。', answer: '0', explanation: '配列の添字は 0 始まりです。', common_mistakes: '1 と書くと 20 を取ってしまいます。' }),
  js({ id: 'local-javascript-008', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: '配列の末尾に追加するメソッド', level: 1, type: 'fill_blank', statement: '`items` 配列の末尾に `"apple"` を追加したいです。空欄を埋めてください。\n\nitems.__________("apple");', hint: 'よく使う追加メソッドです。', answer: 'push', explanation: '`push` は配列の末尾追加で使います。', common_mistakes: '`add` というメソッドは標準配列にはありません。' }),
  js({ id: 'local-javascript-009', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: 'オブジェクトの name を読む記法', level: 1, type: 'fill_blank', statement: '`const user = { name: "Aoki" };` の name を読みたいです。空欄を埋めてください。\n\nuser.__________', hint: 'プロパティ名をそのまま書きます。', answer: 'name', explanation: 'ドット記法でプロパティを読めます。', common_mistakes: '`user["user"]` のようにキー名をずらさないようにします。' }),
  js({ id: 'local-javascript-010', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: 'map で要素を 2 倍にする戻り値', level: 2, type: 'fill_blank', statement: '`numbers.map((num) => __________)` の空欄を埋めて、各要素を 2 倍にしてください。', hint: '引数 `num` を使います。', answer: 'num * 2', explanation: '`map` は各要素から新しい値を返して新配列を作ります。', common_mistakes: '`numbers * 2` のように配列全体を直接掛け算はできません。' }),
  js({ id: 'local-javascript-011', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: '偶数だけに絞る filter を書く', level: 2, type: 'code', statement: '`const numbers = [1, 2, 3, 4];` から偶数だけを取り出して `evens` に入れるコードを書いてください。', requirements: '`filter` を使うこと', hint: '`num % 2 === 0` が条件です。', answer: 'const evens = numbers.filter((num) => num % 2 === 0);', explanation: '`filter` は条件に合う要素だけを残すときに使います。', common_mistakes: '`map` を使うと絞り込みではなく変換になります。' }),
  js({ id: 'local-javascript-012', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: 'name だけの配列を作る map を書く', level: 2, type: 'code', statement: '`const users = [{ name: "Aoki" }, { name: "Sato" }];` から name だけの配列 `names` を作るコードを書いてください。', requirements: '`map` を使うこと', hint: '`user.name` を返します。', answer: 'const names = users.map((user) => user.name);', explanation: '`map` はプロパティ抽出でもよく使います。', common_mistakes: '`filter` を使うと要素数は変わりません。' }),
  js({ id: 'local-javascript-013', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: 'reduce で合計を求める', level: 2, type: 'code', statement: '`const prices = [100, 200, 300];` の合計を `total` に入れるコードを書いてください。', requirements: '`reduce` を使うこと', hint: '初期値は 0 です。', answer: 'const total = prices.reduce((sum, price) => sum + price, 0);', explanation: '`reduce` は集約処理の基本です。', common_mistakes: '初期値を省くと意図しない動きになることがあります。' }),
  js({ id: 'local-javascript-014', theme_id: 'local-javascript-array-object', themeName: 'JavaScript: 配列 / オブジェクト', title: '新しい key を追加したオブジェクトを作る', level: 2, type: 'code', statement: '`const user = { name: "Aoki" };` をもとに、`age: 25` を追加した新しいオブジェクト `updatedUser` を作るコードを書いてください。', requirements: 'スプレッド構文を使うこと', hint: '`...user` を使います。', answer: 'const updatedUser = {\n  ...user,\n  age: 25,\n};', explanation: '既存オブジェクトを壊さずに更新するときはスプレッド構文が便利です。', common_mistakes: '元の user を直接書き換えると副作用が増えやすくなります。' }),
  js({ id: 'local-javascript-015', theme_id: 'local-javascript-function-scope', themeName: 'JavaScript: 関数 / スコープ', title: 'アロー関数の矢印記法', level: 1, type: 'fill_blank', statement: '`const add = (a, b) __________ a + b;` の空欄を埋めてください。', hint: 'アロー関数で使う記号です。', answer: '=>', explanation: 'アロー関数は `=>` で書きます。', common_mistakes: '`->` は JavaScript の記法ではありません。' }),
  js({ id: 'local-javascript-016', theme_id: 'local-javascript-function-scope', themeName: 'JavaScript: 関数 / スコープ', title: '関数内だけで使える変数宣言', level: 1, type: 'fill_blank', statement: 'ブロック内だけで使う変数 `count` を宣言したいです。空欄を埋めてください。\n\n__________ count = 0;', hint: '`var` よりスコープが狭い宣言です。', answer: 'let', explanation: '`let` はブロックスコープを持つ変数宣言です。', common_mistakes: '`var` は関数スコープで、意図より広く見えてしまうことがあります。' }),
  js({ id: 'local-javascript-017', theme_id: 'local-javascript-function-scope', themeName: 'JavaScript: 関数 / スコープ', title: '値を返すキーワード', level: 1, type: 'fill_blank', statement: '関数から計算結果を返したいです。空欄を埋めてください。\n\n__________ total;', hint: '関数の結果を呼び出し元へ返すときに使います。', answer: 'return', explanation: '`return` で関数の戻り値を返します。', common_mistakes: '`console.log` は表示であって戻り値ではありません。' }),
  js({ id: 'local-javascript-018', theme_id: 'local-javascript-function-scope', themeName: 'JavaScript: 関数 / スコープ', title: '2 つの数を足す関数を書く', level: 1, type: 'code', statement: '`a` と `b` を受け取り、足し算結果を返す `add` 関数を書いてください。', requirements: '通常の function 構文で書くこと', hint: '`return a + b;` を返します。', answer: 'function add(a, b) {\n  return a + b;\n}', explanation: '通常の関数定義の基本形です。', common_mistakes: '戻り値を書かないと計算結果を再利用できません。' }),
  js({ id: 'local-javascript-019', theme_id: 'local-javascript-function-scope', themeName: 'JavaScript: 関数 / スコープ', title: '関数式で greet を書く', level: 2, type: 'code', statement: '`name` を受け取り `Hello, ${name}` を返すアロー関数 `greet` を書いてください。', requirements: 'アロー関数で書くこと', hint: 'テンプレートリテラルを使います。', answer: 'const greet = (name) => `Hello, ${name}`;', explanation: '短い関数はアロー関数で簡潔に書けます。', common_mistakes: '波かっこを付けたのに return を忘れると undefined になります。' }),
  js({ id: 'local-javascript-020', theme_id: 'local-javascript-function-scope', themeName: 'JavaScript: 関数 / スコープ', title: 'ブロックスコープの違いを確認するコードを書く', level: 2, type: 'code', statement: 'if ブロック内でだけ使う `message` を宣言し、その中で `console.log(message)` するコードを書いてください。宣言には `const` を使ってください。', requirements: 'if 文と const を使うこと', hint: 'ブロック内で完結させます。', answer: 'if (true) {\n  const message = "ok";\n  console.log(message);\n}', explanation: 'ブロック内だけで完結する値は狭いスコープで宣言する方が安全です。', common_mistakes: '外に置く必要のない変数まで外に出すと見通しが悪くなります。' }),
  js({ id: 'local-javascript-021', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'Promise 成功時に使うメソッド', level: 1, type: 'fill_blank', statement: '`fetchData().__________((data) => console.log(data));` の空欄を埋めてください。', hint: '成功時の処理をつなぐメソッドです。', answer: 'then', explanation: '`then` は Promise 成功時の値を受け取るときに使います。', common_mistakes: '`catch` はエラー時です。' }),
  js({ id: 'local-javascript-022', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'await を使う関数宣言', level: 1, type: 'fill_blank', statement: '`await` を使える関数にしたいです。空欄を埋めてください。\n\n__________ function loadData() {', hint: '`await` の前提になる宣言です。', answer: 'async', explanation: '`await` は `async function` の中で使います。', common_mistakes: '`function` だけでは await は使えません。' }),
  js({ id: 'local-javascript-023', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'Promise の失敗時に使うメソッド', level: 1, type: 'fill_blank', statement: '`fetchData().then(...).__________((error) => console.error(error));` の空欄を埋めてください。', hint: 'エラーハンドリング用です。', answer: 'catch', explanation: '`catch` は Promise の失敗時処理で使います。', common_mistakes: '`finally` は成功失敗どちらでも動きますが、エラー内容受け取りの主役ではありません。' }),
  js({ id: 'local-javascript-024', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'JSON 変換で使うメソッド', level: 1, type: 'fill_blank', statement: '`const data = await response.__________();` の空欄を埋めてください。', hint: 'fetch のレスポンスを JSON として読むメソッドです。', answer: 'json', explanation: '`response.json()` で JSON 本文を JavaScript の値に変換できます。', common_mistakes: '`body()` というメソッドは標準ではありません。' }),
  js({ id: 'local-javascript-025', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'async/await で fetch する関数を書く', level: 2, type: 'code', statement: '`/api/tasks` に `fetch` し、レスポンスを JSON で返す `loadTasks` 関数を書いてください。', requirements: '`async`, `await`, `response.json()` を使うこと', hint: 'fetch の結果を response に受けます。', answer: 'async function loadTasks() {\n  const response = await fetch("/api/tasks");\n  return response.json();\n}', explanation: 'fetch と JSON 変換の基本形です。', common_mistakes: '`await` を付け忘れると Promise のままになります。' }),
  js({ id: 'local-javascript-026', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'Promise の then で title を出力する', level: 2, type: 'code', statement: '`fetchTask()` が Promise で `{ title: "Learn JS" }` を返すとき、`then` を使って title を `console.log` するコードを書いてください。', requirements: '`then` を使うこと', hint: 'then の引数で task を受けます。', answer: 'fetchTask().then((task) => {\n  console.log(task.title);\n});', explanation: 'Promise の値を then で受け取る基本形です。', common_mistakes: 'Promise 自体をそのまま console.log しても中身の title は出ません。' }),
  js({ id: 'local-javascript-027', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'try/catch でエラーを拾う async 関数を書く', level: 2, type: 'code', statement: '`fetch("/api/tasks")` を await し、失敗したら `console.error(error)` する `loadTasks` 関数を書いてください。', requirements: 'async と try/catch を使うこと', hint: 'try の中で await、catch で error を受けます。', answer: 'async function loadTasks() {\n  try {\n    const response = await fetch("/api/tasks");\n    return await response.json();\n  } catch (error) {\n    console.error(error);\n  }\n}', explanation: '非同期処理でも try/catch でエラーハンドリングできます。', common_mistakes: 'catch を付けないと失敗時の扱いが曖昧になります。' }),
  js({ id: 'local-javascript-028', theme_id: 'local-javascript-async', themeName: 'JavaScript: 非同期', title: 'Promise.all の用途を説明する', level: 2, type: 'code', statement: '`Promise.all([fetchA(), fetchB()])` が何をするコードなのかを 1 文で説明してください。', requirements: '複数 Promise をまとめて待つことに触れてください。', hint: 'A と B が終わるのを両方待ちます。', answer: '複数の Promise がすべて完了するのをまとめて待ち、その結果を一度に受け取るためのコードです。', explanation: '並列で複数の非同期処理を扱う基本知識です。', common_mistakes: '1 つだけ完了した時点で終わるわけではありません。' }),
  js({ id: 'local-javascript-029', theme_id: 'local-javascript-dom', themeName: 'JavaScript: DOM操作', title: 'ID で要素を取るメソッド', level: 1, type: 'fill_blank', statement: '`<div id="message"></div>` を取得したいです。空欄を埋めてください。\n\ndocument.__________("message")', hint: 'id 指定で取るときの標準メソッドです。', answer: 'getElementById', explanation: '`getElementById` は id 指定で DOM 要素を取得します。', common_mistakes: '`querySelector` でも取れますが、この問題は専用メソッド前提です。' }),
  js({ id: 'local-javascript-030', theme_id: 'local-javascript-dom', themeName: 'JavaScript: DOM操作', title: 'クラスで 1 件取得するメソッド', level: 1, type: 'fill_blank', statement: '`.item` に一致する最初の要素を取得したいです。空欄を埋めてください。\n\ndocument.__________(".item")', hint: 'CSS セレクタ形式で指定します。', answer: 'querySelector', explanation: '`querySelector` は CSS セレクタで最初の 1 件を取れます。', common_mistakes: '`getElementById` ではクラス指定をそのまま使えません。' }),
  js({ id: 'local-javascript-031', theme_id: 'local-javascript-dom', themeName: 'JavaScript: DOM操作', title: 'クリックイベント登録メソッド', level: 1, type: 'fill_blank', statement: '`button` にクリックイベントを付けたいです。空欄を埋めてください。\n\nbutton.__________("click", handleClick)', hint: 'イベント登録でよく使うメソッドです。', answer: 'addEventListener', explanation: '`addEventListener` で DOM イベントを登録できます。', common_mistakes: '`onClick` は JSX などでは見ることがありますが、生 DOM では別物です。' }),
  js({ id: 'local-javascript-032', theme_id: 'local-javascript-dom', themeName: 'JavaScript: DOM操作', title: '要素のテキストを書き換えるコードを書く', level: 2, type: 'code', statement: '`id="message"` の要素のテキストを `完了しました` に変えるコードを書いてください。', requirements: '`getElementById` と `textContent` を使うこと', hint: '取得してから textContent に代入します。', answer: 'const message = document.getElementById("message");\nmessage.textContent = "完了しました";', explanation: 'テキスト更新は DOM 操作の基本です。', common_mistakes: '`innerHTML` を乱用すると不要な HTML 解釈が入ることがあります。' }),
  js({ id: 'local-javascript-033', theme_id: 'local-javascript-dom', themeName: 'JavaScript: DOM操作', title: 'ボタンにクリック時ログを付ける', level: 2, type: 'code', statement: '`id="saveButton"` のボタンにクリック時 `saved` と出すイベントを付けるコードを書いてください。', requirements: '`addEventListener` を使うこと', hint: '最初にボタン要素を取得します。', answer: 'const saveButton = document.getElementById("saveButton");\nsaveButton.addEventListener("click", () => {\n  console.log("saved");\n});', explanation: 'イベント登録の基本形です。', common_mistakes: '取得前に addEventListener を呼ぶと要素がなくて失敗することがあります。' }),
  js({ id: 'local-javascript-034', theme_id: 'local-javascript-dom', themeName: 'JavaScript: DOM操作', title: '入力欄の value を読むコードを書く', level: 2, type: 'code', statement: '`id="taskInput"` の input 要素の値を `const title` に入れるコードを書いてください。', requirements: 'DOM 取得と `.value` を使うこと', hint: 'input 要素を取ってから value を読みます。', answer: 'const taskInput = document.getElementById("taskInput");\nconst title = taskInput.value;', explanation: 'フォーム入力を扱うときの基本です。', common_mistakes: '`textContent` を使うと input の入力値は取れません。' }),
  js({ id: 'local-javascript-035', theme_id: 'local-javascript-api', themeName: 'JavaScript: API通信', title: 'GET 通信で使う fetch', level: 1, type: 'fill_blank', statement: 'JavaScript で `/api/tasks` に GET 通信したいです。空欄を埋めてください。\n\n__________("/api/tasks")', hint: '標準の HTTP 通信 API です。', answer: 'fetch', explanation: 'ブラウザ標準の通信関数として `fetch` がよく使われます。', common_mistakes: '`axios` もありますが、標準 API ではありません。' }),
  js({ id: 'local-javascript-036', theme_id: 'local-javascript-api', themeName: 'JavaScript: API通信', title: 'POST の method 指定', level: 1, type: 'fill_blank', statement: 'fetch のオプションで POST 通信にしたいです。空欄を埋めてください。\n\n{ __________: "POST" }', hint: 'HTTP メソッドを指定するキーです。', answer: 'method', explanation: '`method` キーで GET / POST などを指定します。', common_mistakes: '`type` では HTTP メソッド指定になりません。' }),
  js({ id: 'local-javascript-037', theme_id: 'local-javascript-api', themeName: 'JavaScript: API通信', title: 'JSON 文字列化に使う関数', level: 1, type: 'fill_blank', statement: '送信するオブジェクトを JSON 文字列へ変換したいです。空欄を埋めてください。\n\n__________(data)', hint: '組み込みの JSON オブジェクトを使います。', answer: 'JSON.stringify', explanation: '`JSON.stringify` でオブジェクトを文字列へ変換できます。', common_mistakes: '`JSON.parse` は逆方向です。' }),
  js({ id: 'local-javascript-038', theme_id: 'local-javascript-api', themeName: 'JavaScript: API通信', title: 'POST でタイトルを送る fetch を書く', level: 2, type: 'code', statement: '`title` という値を `/api/tasks` へ POST 送信する `fetch` コードを書いてください。body は JSON、header には `Content-Type: application/json` を入れてください。', requirements: '`method`, `headers`, `body` を含めること', hint: 'body には `JSON.stringify({ title })` を使います。', answer: 'fetch("/api/tasks", {\n  method: "POST",\n  headers: {\n    "Content-Type": "application/json",\n  },\n  body: JSON.stringify({ title }),\n});', explanation: 'JSON 送信の基本形です。', common_mistakes: 'body にオブジェクトをそのまま入れると期待どおり送れません。' }),
  js({ id: 'local-javascript-039', theme_id: 'local-javascript-api', themeName: 'JavaScript: API通信', title: 'fetch 後に JSON を読む async 関数を書く', level: 2, type: 'code', statement: '`/api/users` を fetch して JSON を返す `loadUsers` 関数を書いてください。', requirements: 'async / await を使うこと', hint: 'response.json() を返します。', answer: 'async function loadUsers() {\n  const response = await fetch("/api/users");\n  return response.json();\n}', explanation: 'API 通信の最小形としてよく出ます。', common_mistakes: '`await` を忘れると response が Promise ではなくならない点に注意します。' }),
  js({ id: 'local-javascript-040', theme_id: 'local-javascript-api', themeName: 'JavaScript: API通信', title: '取得した tasks を console に出すコードを書く', level: 2, type: 'code', statement: '`loadTasks()` が tasks 配列を Promise で返すとき、async/await を使って tasks を `console.log` するコードを書いてください。', requirements: 'async 関数の中で await すること', hint: '先に結果を変数で受けると見やすいです。', answer: 'async function showTasks() {\n  const tasks = await loadTasks();\n  console.log(tasks);\n}', explanation: '非同期取得した値を使うには await で待つ必要があります。', common_mistakes: 'Promise のまま console.log すると配列本体ではなく Promise が見えます。' }),
]
