type ProblemSeed = {
  id: string
  theme_id: string
  themeName: string
  title: string
  level: number
  type: string
  statement: string
  requirements?: string
  hint: string
  answer: string
  explanation: string
  common_mistakes: string
}

const react = (problem: ProblemSeed): ProblemSeed => problem

export const REACT_PROBLEM_SEEDS: ProblemSeed[] = [
  react({ id: 'local-react-001', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'JSX を返すキーワード', level: 1, type: 'fill_blank', statement: '関数コンポーネントの中で JSX を返したいです。空欄を埋めてください。\n\n__________ <h1>Hello</h1>;', hint: '関数の戻り値です。', answer: 'return', explanation: '関数コンポーネントは JSX を return して描画します。', common_mistakes: 'JSX を書いただけでは描画されません。' }),
  react({ id: 'local-react-002', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'JSX で class 属性に使う名前', level: 1, type: 'fill_blank', statement: 'React の JSX で CSS クラスを付けたいです。空欄を埋めてください。\n\n<div __________="card">', hint: 'HTML の class とは少し違う名前です。', answer: 'className', explanation: 'JSX では `class` ではなく `className` を使います。', common_mistakes: 'HTML の感覚で `class` と書くと警告や不具合の原因になります。' }),
  react({ id: 'local-react-003', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'JSX で JavaScript 値を埋め込む記号', level: 1, type: 'fill_blank', statement: 'props.title を JSX に表示したいです。空欄を埋めてください。\n\n<h1>__________</h1>', hint: '波かっこを使います。', answer: '{props.title}', explanation: 'JSX では波かっこ内に JavaScript 式を書けます。', common_mistakes: '`$` やテンプレートリテラルの形は JSX ではそのまま使いません。' }),
  react({ id: 'local-react-004', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'Hello を表示する関数コンポーネントを書く', level: 1, type: 'code', statement: '`HelloMessage` という名前の関数コンポーネントを書いてください。表示内容は `<p>Hello</p>` だけで構いません。', requirements: '関数コンポーネントで書くこと', hint: 'return で JSX を返します。', answer: 'function HelloMessage() {\n  return <p>Hello</p>;\n}', explanation: '関数コンポーネントの最小形です。', common_mistakes: '関数名を小文字にするとコンポーネントとして扱われにくくなります。' }),
  react({ id: 'local-react-005', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'title を表示する TaskCard コンポーネントを書く', level: 1, type: 'code', statement: '`title` を props で受け取り、`<div>{title}</div>` を返す `TaskCard` コンポーネントを書いてください。', requirements: 'props を受け取ること', hint: '引数に props を受けて `props.title` を使えます。', answer: 'function TaskCard(props) {\n  return <div>{props.title}</div>;\n}', explanation: 'props を受け取ることで外から値を渡せます。', common_mistakes: 'コンポーネント内で title 変数が未定義のまま使われないようにします。' }),
  react({ id: 'local-react-006', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: '配列を li で描画する JSX を書く', level: 2, type: 'code', statement: '`const tasks = ["A", "B"];` を使って、`ul` の中に `li` を 2 件並べる JSX を `map` で書いてください。', requirements: '`map` と `key` を使うこと', hint: '`task` 自体を key にして構いません。', answer: 'return (\n  <ul>\n    {tasks.map((task) => (\n      <li key={task}>{task}</li>\n    ))}\n  </ul>\n);', explanation: '一覧描画は React の基本パターンです。', common_mistakes: 'key を付けないと一覧更新時の挙動が分かりづらくなります。' }),
  react({ id: 'local-react-007', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'デフォルト export の書き方', level: 1, type: 'fill_blank', statement: '`App` コンポーネントをデフォルト export したいです。空欄を埋めてください。\n\n__________ App;', hint: 'ファイルの代表として外へ出すキーワードです。', answer: 'export default', explanation: '`export default` でそのファイルの主要コンポーネントを外へ出せます。', common_mistakes: '`export` だけだと import 側の書き方が変わります。' }),
  react({ id: 'local-react-008', theme_id: 'local-react-basic', themeName: 'React: 基礎（JSX / コンポーネント）', title: 'loading が true のときだけ文言を返す', level: 2, type: 'code', statement: '`loading` が true のときだけ `<p>Loading...</p>` を返す `if` 文を書いてください。', requirements: 'return を含めること', hint: 'ガード節の形です。', answer: 'if (loading) {\n  return <p>Loading...</p>;\n}', explanation: '先に特別ケースを返すと見通しが良くなります。', common_mistakes: 'JSX の外で文字列だけ返すと表示形式がずれることがあります。' }),
  react({ id: 'local-react-009', theme_id: 'local-react-state', themeName: 'React: state', title: 'state 管理に使うフック名', level: 1, type: 'fill_blank', statement: 'コンポーネントの状態を持ちたいです。空欄を埋めてください。\n\nconst [count, setCount] = __________(0);', hint: 'もっとも基本の状態フックです。', answer: 'useState', explanation: '`useState` は React の基本的な状態管理フックです。', common_mistakes: '`useEffect` は副作用用で、状態そのものを持つものではありません。' }),
  react({ id: 'local-react-010', theme_id: 'local-react-state', themeName: 'React: state', title: 'setCount の役割', level: 1, type: 'fill_blank', statement: '`const [count, __________] = useState(0);` の空欄を埋めてください。', hint: 'count を更新する関数名です。', answer: 'setCount', explanation: 'useState の 2 つ目は状態更新関数です。', common_mistakes: 'count 自体に代入しても React の再描画にはつながりません。' }),
  react({ id: 'local-react-011', theme_id: 'local-react-state', themeName: 'React: state', title: '初期値 0 の state を作る', level: 1, type: 'fill_blank', statement: '`const [count, setCount] = useState(__________);` の空欄を埋めてください。', hint: '数値 0 です。', answer: '0', explanation: 'state は初期値から始まります。', common_mistakes: '`"0"` のような文字列にすると型や挙動がずれます。' }),
  react({ id: 'local-react-012', theme_id: 'local-react-state', themeName: 'React: state', title: 'カウントを 1 増やすボタンを書く', level: 1, type: 'code', statement: '`count` と `setCount` がある前提で、クリック時に `count + 1` するボタン JSX を書いてください。', requirements: '`onClick` を使うこと', hint: '`setCount(count + 1)` を呼びます。', answer: '<button onClick={() => setCount(count + 1)}>増やす</button>', explanation: 'state 更新は setter 関数で行います。', common_mistakes: 'count++ のような直接変更は React の状態更新ではありません。' }),
  react({ id: 'local-react-013', theme_id: 'local-react-state', themeName: 'React: state', title: 'true / false を切り替える state 更新を書く', level: 2, type: 'code', statement: '`isOpen` と `setIsOpen` がある前提で、現在値を反転させるコードを書いてください。', requirements: 'setIsOpen を使うこと', hint: '`!isOpen` を渡します。', answer: 'setIsOpen(!isOpen);', explanation: '真偽値の切り替えは反転で書けます。', common_mistakes: '`isOpen = !isOpen` は state 更新になりません。' }),
  react({ id: 'local-react-014', theme_id: 'local-react-state', themeName: 'React: state', title: '入力値を state に入れる onChange を書く', level: 2, type: 'code', statement: '`setTitle` がある前提で、input の変更時に `e.target.value` を state へ入れる `onChange` を書いてください。', requirements: 'アロー関数で書くこと', hint: '引数 e を受けます。', answer: 'onChange={(e) => setTitle(e.target.value)}', explanation: '入力フォームの state 管理は controlled component の基本です。', common_mistakes: 'e.value ではなく `e.target.value` を使います。' }),
  react({ id: 'local-react-015', theme_id: 'local-react-state', themeName: 'React: state', title: '配列 state に新しい要素を追加する', level: 2, type: 'code', statement: '`tasks` と `setTasks` がある前提で、文字列 `"Study"` を末尾追加するコードを書いてください。', requirements: 'スプレッド構文を使うこと', hint: '`[...tasks, "Study"]` の形です。', answer: 'setTasks([...tasks, "Study"]);', explanation: '配列 state は新しい配列を作って更新します。', common_mistakes: '`tasks.push("Study")` は既存配列を直接変更してしまいます。' }),
  react({ id: 'local-react-016', theme_id: 'local-react-state', themeName: 'React: state', title: '入力フォームを空文字で初期化する state を作る', level: 1, type: 'code', statement: '`title` と `setTitle` を持つ state を、初期値が空文字になるように書いてください。', hint: '`useState("")` です。', answer: 'const [title, setTitle] = useState("");', explanation: '文字列入力用 state の典型的な初期値は空文字です。', common_mistakes: '`null` から始めると input の value と扱いがずれることがあります。' }),
  react({ id: 'local-react-017', theme_id: 'local-react-props', themeName: 'React: props', title: 'props を分割代入する記法', level: 1, type: 'fill_blank', statement: '`function TaskCard(__________) {` の空欄を埋めて、`title` を分割代入で受け取ってください。', hint: '波かっこで囲みます。', answer: '{ title }', explanation: 'props は関数引数で分割代入できます。', common_mistakes: '`title` だけだとオブジェクト分解になりません。' }),
  react({ id: 'local-react-018', theme_id: 'local-react-props', themeName: 'React: props', title: 'props.title を表示する JSX', level: 1, type: 'fill_blank', statement: '`function TaskCard(props) { return <p>__________</p>; }` の空欄を埋めてください。', hint: 'props オブジェクトから title を読みます。', answer: '{props.title}', explanation: 'props 経由で親から渡された値を表示できます。', common_mistakes: '`{title}` と書くなら引数側で分割代入が必要です。' }),
  react({ id: 'local-react-019', theme_id: 'local-react-props', themeName: 'React: props', title: 'title prop を表示する子コンポーネントを書く', level: 1, type: 'code', statement: '`title` を props で受け取り `<h2>{title}</h2>` を返す `TaskTitle` コンポーネントを書いてください。', requirements: '分割代入で受け取ってください。', hint: '`function TaskTitle({ title })` の形です。', answer: 'function TaskTitle({ title }) {\n  return <h2>{title}</h2>;\n}', explanation: 'props を必要な分だけ受け取ると読みやすくなります。', common_mistakes: 'props 全体を受けたのに title を直接参照すると未定義になります。' }),
  react({ id: 'local-react-020', theme_id: 'local-react-props', themeName: 'React: props', title: 'onDelete prop をボタンへつなぐ', level: 2, type: 'code', statement: '`onDelete` を props で受け取り、クリック時にそれを実行するボタン JSX を書いてください。', requirements: '`onClick={onDelete}` の形で書くこと', hint: '今回は追加引数はありません。', answer: '<button onClick={onDelete}>削除</button>', explanation: '親から受けた関数を子のイベントへそのまま渡すのはよくある形です。', common_mistakes: '`onClick={onDelete()}` とすると描画時に実行されます。' }),
  react({ id: 'local-react-021', theme_id: 'local-react-props', themeName: 'React: props', title: 'isDone に応じて文言を分ける JSX を書く', level: 2, type: 'code', statement: '`isDone` を props で受け取り、true なら `<span>完了</span>`、false なら `<span>未完了</span>` を返す JSX を書いてください。', requirements: '三項演算子を使うこと', hint: '`isDone ? ... : ...` です。', answer: '{isDone ? <span>完了</span> : <span>未完了</span>}', explanation: 'props に応じた表示分岐は React の基本です。', common_mistakes: 'if 文を JSX の中へそのまま書くことはできません。' }),
  react({ id: 'local-react-022', theme_id: 'local-react-props', themeName: 'React: props', title: '親から task を渡して子を呼ぶ JSX を書く', level: 2, type: 'code', statement: '`task` 変数がある前提で、`TaskItem` コンポーネントへ `task` prop を渡す JSX を書いてください。', requirements: 'prop 名は task にしてください。', hint: 'JSX 属性で渡します。', answer: '<TaskItem task={task} />', explanation: 'オブジェクト props をそのまま渡すのもよく使います。', common_mistakes: '`task="task"` とすると文字列になってしまいます。' }),
  react({ id: 'local-react-023', theme_id: 'local-react-event', themeName: 'React: イベント処理', title: 'クリックイベント属性名', level: 1, type: 'fill_blank', statement: 'React のボタンでクリックイベントを付けたいです。空欄を埋めてください。\n\n<button __________={handleClick}>', hint: 'camelCase です。', answer: 'onClick', explanation: 'React のイベント属性は camelCase で書きます。', common_mistakes: '`onclick` は HTML 属性で、React では使いません。' }),
  react({ id: 'local-react-024', theme_id: 'local-react-event', themeName: 'React: イベント処理', title: '入力値を読む式', level: 1, type: 'fill_blank', statement: 'onChange の引数 `event` から入力値を取りたいです。空欄を埋めてください。\n\nevent.__________', hint: 'target の value までたどります。', answer: 'target.value', explanation: 'React の入力イベントでも `event.target.value` を使います。', common_mistakes: '`event.value` では値を直接取れません。' }),
  react({ id: 'local-react-025', theme_id: 'local-react-event', themeName: 'React: イベント処理', title: 'submit を止める handleSubmit を書く', level: 2, type: 'code', statement: 'フォーム送信時の再読み込みを止める `handleSubmit` 関数を書いてください。', requirements: '`event.preventDefault()` を使うこと', hint: '引数 event を受けます。', answer: 'function handleSubmit(event) {\n  event.preventDefault();\n}', explanation: 'フォーム送信の既定動作を止める基本コードです。', common_mistakes: 'preventDefault を呼ばないと画面再読み込みが起きやすくなります。' }),
  react({ id: 'local-react-026', theme_id: 'local-react-event', themeName: 'React: イベント処理', title: '保存ボタンに handleSave を付ける JSX', level: 1, type: 'code', statement: '`handleSave` をクリック時に呼ぶボタン JSX を書いてください。表示文言は `保存` にしてください。', requirements: '`onClick={handleSave}` を使うこと', hint: '今回は追加引数は不要です。', answer: '<button onClick={handleSave}>保存</button>', explanation: 'イベントハンドラを props やローカル関数でつなぐ基本形です。', common_mistakes: '`handleSave()` と書くと即実行になります。' }),
  react({ id: 'local-react-027', theme_id: 'local-react-event', themeName: 'React: イベント処理', title: 'task.id を渡して削除する onClick を書く', level: 2, type: 'code', statement: '`handleDelete` と `task.id` がある前提で、クリック時に `handleDelete(task.id)` を呼ぶボタン JSX を書いてください。', requirements: 'アロー関数で包むこと', hint: '引数ありのときはその場で関数を作ります。', answer: '<button onClick={() => handleDelete(task.id)}>削除</button>', explanation: '引数付きでイベントを渡すときの定番です。', common_mistakes: '`onClick={handleDelete(task.id)}` だと描画時に実行されます。' }),
  react({ id: 'local-react-028', theme_id: 'local-react-event', themeName: 'React: イベント処理', title: 'チェックボックスの checked を state へ入れる', level: 2, type: 'code', statement: '`setIsDone` がある前提で、checkbox の変更時に `event.target.checked` を state へ入れる `onChange` を書いてください。', requirements: 'checked を使うこと', hint: 'checkbox は value ではなく checked を見ます。', answer: 'onChange={(event) => setIsDone(event.target.checked)}', explanation: 'checkbox では checked を使うのが基本です。', common_mistakes: 'value を見ると true/false ではなく文字列扱いになりやすいです。' }),
  react({ id: 'local-react-029', theme_id: 'local-react-form', themeName: 'React: フォーム', title: 'controlled input の値属性名', level: 1, type: 'fill_blank', statement: 'input を controlled component にしたいです。state 変数 `title` をつなぐ空欄を埋めてください。\n\n<input __________={title} />', hint: '入力欄の現在値を表す属性です。', answer: 'value', explanation: 'controlled input は state を value に結び付けます。', common_mistakes: '`defaultValue` は初期値だけで、その後の状態同期とは役割が違います。' }),
  react({ id: 'local-react-030', theme_id: 'local-react-form', themeName: 'React: フォーム', title: 'textarea の変更イベント属性名', level: 1, type: 'fill_blank', statement: 'textarea の内容変化を拾いたいです。空欄を埋めてください。\n\n<textarea __________={handleChange} />', hint: 'input と同じイベント属性です。', answer: 'onChange', explanation: 'textarea でも `onChange` を使います。', common_mistakes: '`onInput` よりも React では `onChange` が基本です。' }),
  react({ id: 'local-react-031', theme_id: 'local-react-form', themeName: 'React: フォーム', title: 'title 入力欄の controlled input を書く', level: 2, type: 'code', statement: '`title` と `setTitle` がある前提で、value と onChange を持つ text input JSX を書いてください。', requirements: '`event.target.value` を使うこと', hint: 'input の value と setTitle を結びます。', answer: '<input value={title} onChange={(event) => setTitle(event.target.value)} />', explanation: 'value と onChange の 2 点セットが controlled input の基本です。', common_mistakes: 'value だけ付けて onChange がないと入力できなくなります。' }),
  react({ id: 'local-react-032', theme_id: 'local-react-form', themeName: 'React: フォーム', title: 'status を選ぶ select を書く', level: 2, type: 'code', statement: '`status` と `setStatus` がある前提で、`todo` と `done` を選べる select JSX を書いてください。', requirements: 'value と onChange を持つこと', hint: 'option を 2 つ書きます。', answer: '<select value={status} onChange={(event) => setStatus(event.target.value)}>\n  <option value="todo">todo</option>\n  <option value="done">done</option>\n</select>', explanation: 'select も controlled component として扱えます。', common_mistakes: 'selected 属性を個別 option に付けるより、React では select 全体の value を管理する方が自然です。' }),
  react({ id: 'local-react-033', theme_id: 'local-react-form', themeName: 'React: フォーム', title: 'title と description を送信するフォームを書く', level: 2, type: 'code', statement: '`title`, `setTitle`, `description`, `setDescription`, `handleSubmit` がある前提で、2 つの入力欄と送信ボタンを持つフォーム JSX を書いてください。', requirements: 'form の onSubmit を使うこと', hint: 'input と textarea の組み合わせです。', answer: '<form onSubmit={handleSubmit}>\n  <input value={title} onChange={(event) => setTitle(event.target.value)} />\n  <textarea value={description} onChange={(event) => setDescription(event.target.value)} />\n  <button type="submit">保存</button>\n</form>', explanation: '複数入力をまとめて送るフォームの基本形です。', common_mistakes: 'button の type を省くと意図が伝わりにくくなります。' }),
  react({ id: 'local-react-034', theme_id: 'local-react-form', themeName: 'React: フォーム', title: '送信後にフォームを初期化するコードを書く', level: 2, type: 'code', statement: '送信成功後に `title` と `description` を空文字へ戻すコードを書いてください。', requirements: 'setTitle と setDescription を使うこと', hint: '両方とも空文字へ戻します。', answer: 'setTitle("");\nsetDescription("");', explanation: '送信後にフォームをリセットするのは実務でもよくあります。', common_mistakes: '片方だけ戻すと UI 状態が中途半端になります。' }),
  react({ id: 'local-react-035', theme_id: 'local-react-api', themeName: 'React: API連携', title: '副作用で使うフック名', level: 1, type: 'fill_blank', statement: '初回表示時に API を呼びたいです。空欄を埋めてください。\n\n__________(() => {', hint: '副作用処理の基本フックです。', answer: 'useEffect', explanation: '`useEffect` はデータ取得などの副作用で使います。', common_mistakes: '`useState` は状態保持用で、API 実行タイミングの管理役ではありません。' }),
  react({ id: 'local-react-036', theme_id: 'local-react-api', themeName: 'React: API連携', title: 'HTTP 通信に使う関数名', level: 1, type: 'fill_blank', statement: 'ブラウザ標準で `/api/tasks` を取得したいです。空欄を埋めてください。\n\n__________("/api/tasks")', hint: 'JavaScript 標準の通信 API です。', answer: 'fetch', explanation: 'React でも標準通信は `fetch` をよく使います。', common_mistakes: '`axios` もありますが、この問題は標準 API 前提です。' }),
  react({ id: 'local-react-037', theme_id: 'local-react-api', themeName: 'React: API連携', title: 'レスポンスを JSON にするメソッド', level: 1, type: 'fill_blank', statement: '`const data = await response.__________();` の空欄を埋めてください。', hint: 'JSON へ変換するメソッドです。', answer: 'json', explanation: '`response.json()` でレスポンス本文をオブジェクトへ変換できます。', common_mistakes: '`parse()` ではありません。' }),
  react({ id: 'local-react-038', theme_id: 'local-react-api', themeName: 'React: API連携', title: '初回表示で tasks を取得する useEffect を書く', level: 2, type: 'code', statement: '`tasks` と `setTasks` がある前提で、`/api/tasks` を取得して JSON 結果を `setTasks` に入れる `useEffect` を書いてください。', requirements: '依存配列は空配列にすること', hint: 'useEffect の中で async 関数を定義して呼ぶ形でも構いません。', answer: 'useEffect(() => {\n  async function loadTasks() {\n    const response = await fetch("/api/tasks");\n    const data = await response.json();\n    setTasks(data);\n  }\n\n  loadTasks();\n}, []);', explanation: '初回取得の典型パターンです。', common_mistakes: '依存配列を省くと再描画のたびに取得が走りやすくなります。' }),
  react({ id: 'local-react-039', theme_id: 'local-react-api', themeName: 'React: API連携', title: 'loading を使う API 取得コードを書く', level: 2, type: 'code', statement: '`setLoading` と `setTasks` がある前提で、取得開始前に loading を true、取得後に false に戻す非同期処理を書いてください。', requirements: 'finally を使うこと', hint: 'try/finally で後片付けします。', answer: 'async function loadTasks() {\n  setLoading(true);\n  try {\n    const response = await fetch("/api/tasks");\n    const data = await response.json();\n    setTasks(data);\n  } finally {\n    setLoading(false);\n  }\n}', explanation: 'loading は成功失敗に関係なく戻す必要があるため finally が便利です。', common_mistakes: '成功時だけ false に戻すと、失敗時に loading が残り続けます。' }),
  react({ id: 'local-react-040', theme_id: 'local-react-api', themeName: 'React: API連携', title: '新しい task を POST 送信するコードを書く', level: 2, type: 'code', statement: '`title` を `/api/tasks` に POST 送信する fetch コードを書いてください。body は JSON にしてください。', requirements: '`method`, `headers`, `body` を含めること', hint: '`Content-Type` は application/json です。', answer: 'await fetch("/api/tasks", {\n  method: "POST",\n  headers: {\n    "Content-Type": "application/json",\n  },\n  body: JSON.stringify({ title }),\n});', explanation: 'React でも送信処理は JavaScript の fetch 基本形です。', common_mistakes: 'body を JSON.stringify しないと正しい JSON になりません。' }),
  react({ id: 'local-react-041', theme_id: 'local-react-api', themeName: 'React: API連携', title: 'API エラーを state に入れるコードを書く', level: 3, type: 'code', statement: '`setErrorMessage` がある前提で、fetch 失敗時に `error.message` を state に入れる try/catch コードを書いてください。', requirements: 'catch で error を受けること', hint: '成功時処理は簡略化して構いません。', answer: 'try {\n  const response = await fetch("/api/tasks");\n  await response.json();\n} catch (error) {\n  setErrorMessage(error.message);\n}', explanation: '失敗時の表示制御まで含めると実務に近づきます。', common_mistakes: 'catch を書かないと失敗時の UI が分かりにくくなります。' }),
  react({ id: 'local-react-042', theme_id: 'local-react-api', themeName: 'React: API連携', title: '初回だけ実行する依存配列', level: 1, type: 'fill_blank', statement: '`useEffect(() => { loadTasks(); }, __________);` の空欄を埋めて、初回だけ実行してください。', hint: '空の配列です。', answer: '[]', explanation: '空配列を渡すと初回マウント時だけ実行されます。', common_mistakes: '配列を省くと再描画ごとに動く可能性があります。' }),
  react({ id: 'local-react-043', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: '子コンポーネントへ値を渡す仕組み名', level: 1, type: 'fill_blank', statement: '親コンポーネントから子コンポーネントへ値を渡す仕組み名を書いてください。\n\n__________', hint: 'React の基本用語です。', answer: 'props', explanation: 'props は親から子へデータや関数を渡す仕組みです。', common_mistakes: 'state は各コンポーネント内の状態で、役割が違います。' }),
  react({ id: 'local-react-044', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: '子コンポーネントを import する記法', level: 1, type: 'fill_blank', statement: '`TaskList` コンポーネントを `./TaskList` から読み込みたいです。空欄を埋めてください。\n\n__________ TaskList from "./TaskList";', hint: 'ES Modules の読み込みです。', answer: 'import', explanation: 'コンポーネント分割後は import で取り込みます。', common_mistakes: '`require` を混ぜると書き方がぶれやすくなります。' }),
  react({ id: 'local-react-045', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: 'TaskList コンポーネントを書く', level: 2, type: 'code', statement: '`tasks` を props で受け取り、`TaskItem` を使って一覧表示する `TaskList` コンポーネントを書いてください。`key` は `task.id` を使ってください。', requirements: '`map` と `TaskItem` を使うこと', hint: '親から受けた tasks をそのまま map します。', answer: 'function TaskList({ tasks }) {\n  return (\n    <ul>\n      {tasks.map((task) => (\n        <TaskItem key={task.id} task={task} />\n      ))}\n    </ul>\n  );\n}', explanation: '一覧責務を切り出すと親コンポーネントが軽くなります。', common_mistakes: 'li の中身を全部親に残したままだと分割の効果が薄れます。' }),
  react({ id: 'local-react-046', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: 'task を表示する TaskItem を書く', level: 2, type: 'code', statement: '`task` を props で受け取り、`<li>{task.title}</li>` を返す `TaskItem` コンポーネントを書いてください。', requirements: 'props は分割代入せず task をそのまま受けても構いません。', hint: '表示責務だけに絞ります。', answer: 'function TaskItem({ task }) {\n  return <li>{task.title}</li>;\n}', explanation: '1 件表示を分けると再利用しやすくなります。', common_mistakes: 'task.title の代わりに title を直接使うなら引数側も合わせる必要があります。' }),
  react({ id: 'local-react-047', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: 'children を受け取る Layout を書く', level: 2, type: 'code', statement: '`children` を props で受け取り、`<main>{children}</main>` を返す `Layout` コンポーネントを書いてください。', requirements: '`children` を表示すること', hint: '分割代入で children を受けると見やすいです。', answer: 'function Layout({ children }) {\n  return <main>{children}</main>;\n}', explanation: 'children を使うとレイアウト部品が作りやすくなります。', common_mistakes: 'children を返さないと内側の要素が表示されません。' }),
  react({ id: 'local-react-048', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: '親から TaskList へ tasks を渡す JSX を書く', level: 1, type: 'code', statement: '`tasks` 変数がある前提で、`TaskList` コンポーネントへ tasks を渡す JSX を書いてください。', hint: 'prop 名も tasks にします。', answer: '<TaskList tasks={tasks} />', explanation: '親から子へ一覧データを渡す基本形です。', common_mistakes: '`tasks="tasks"` にすると文字列が渡ります。' }),
  react({ id: 'local-react-049', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: 'isOpen が false なら何も出さない Modal を書く', level: 3, type: 'code', statement: '`isOpen` と `children` を props で受け取り、`isOpen` が false なら `null`、true なら `<div>{children}</div>` を返す `Modal` コンポーネントを書いてください。', requirements: '早期 return を使って構いません。', hint: '閉じているときは null を返します。', answer: 'function Modal({ isOpen, children }) {\n  if (!isOpen) {\n    return null;\n  }\n\n  return <div>{children}</div>;\n}', explanation: '表示制御を部品側で持たせると親がすっきりします。', common_mistakes: 'false のとき空文字を返すより null の方が React では意図が明確です。' }),
  react({ id: 'local-react-050', theme_id: 'local-react-component-split', themeName: 'React: コンポーネント分割', title: 'TaskPage を小さい部品で組み立てる JSX を書く', level: 3, type: 'code', statement: '`Header`, `TaskForm`, `TaskList` の 3 コンポーネントがある前提で、上から順に並べて返す `TaskPage` コンポーネントを書いてください。`tasks` は `TaskList` へ渡してください。', requirements: '`tasks` prop を使うこと', hint: '大きい画面を小さい部品へ分ける意識です。', answer: 'function TaskPage({ tasks }) {\n  return (\n    <div>\n      <Header />\n      <TaskForm />\n      <TaskList tasks={tasks} />\n    </div>\n  );\n}', explanation: '画面を部品で組み立てる練習は研修でも重要です。', common_mistakes: 'すべてを 1 コンポーネントに詰め込むと責務が重くなります。' }),
]
