type ProblemSeed = {
  id: string
  theme_id: string
  themeName: string
  title: string
  level: number
  type: string
  statement: string
  requirements?: string
  hint: string
  answer: string
  explanation: string
  common_mistakes: string
}

const ts = (problem: ProblemSeed): ProblemSeed => problem

export const TYPESCRIPT_PROBLEM_SEEDS: ProblemSeed[] = [
  ts({ id: 'local-typescript-001', theme_id: 'local-typescript-basic', themeName: 'TypeScript: 型基礎', title: 'string 型の変数を宣言する', level: 1, type: 'code', statement: '`userName` という変数を `string` 型で宣言し、`"Aoki"` を代入するコードを書いてください。', hint: '変数名の後ろに型注釈を書きます。', answer: 'const userName: string = "Aoki";', explanation: 'TypeScript では `変数名: 型` で型注釈を書けます。', common_mistakes: '型注釈を値の後ろに書くことはできません。' }),
  ts({ id: 'local-typescript-002', theme_id: 'local-typescript-basic', themeName: 'TypeScript: 型基礎', title: 'number 型の配列を宣言する', level: 1, type: 'code', statement: '`scores` を number 配列として `[10, 20, 30]` で宣言するコードを書いてください。', hint: '`number[]` の形です。', answer: 'const scores: number[] = [10, 20, 30];', explanation: '配列は `型[]` で型注釈できます。', common_mistakes: '`Array<number>` も別解ですが、この問題は `number[]` で十分です。' }),
  ts({ id: 'local-typescript-003', theme_id: 'local-typescript-basic', themeName: 'TypeScript: 型基礎', title: 'boolean 型のフラグを宣言する', level: 1, type: 'code', statement: '`isAdmin` を `boolean` 型で `false` として宣言するコードを書いてください。', hint: '真偽値型です。', answer: 'const isAdmin: boolean = false;', explanation: '真偽値を表すときは `boolean` を使います。', common_mistakes: '`"false"` のような文字列にしないよう注意します。' }),
  ts({ id: 'local-typescript-004', theme_id: 'local-typescript-basic', themeName: 'TypeScript: 型基礎', title: 'string または null の型を宣言する', level: 2, type: 'code', statement: '`errorMessage` を `string` または `null` で持てるようにし、初期値を `null` にするコードを書いてください。', hint: 'ユニオン型を使います。', answer: 'let errorMessage: string | null = null;', explanation: '複数の型を許すときはユニオン型を使います。', common_mistakes: '`string, null` のような書き方は TypeScript の型になりません。' }),
  ts({ id: 'local-typescript-005', theme_id: 'local-typescript-basic', themeName: 'TypeScript: 型基礎', title: 'リテラル型を使ったステータス変数', level: 2, type: 'code', statement: '`status` に `"idle"` または `"loading"` だけ入るようにして、初期値を `"idle"` にするコードを書いてください。', hint: '文字列リテラル型のユニオンです。', answer: 'let status: "idle" | "loading" = "idle";', explanation: '決まった文字列だけ許したいときはリテラル型が便利です。', common_mistakes: '`string` にすると制約が弱くなります。' }),
  ts({ id: 'local-typescript-006', theme_id: 'local-typescript-basic', themeName: 'TypeScript: 型基礎', title: 'タプル型を宣言する', level: 2, type: 'code', statement: '`point` を `[number, number]` のタプルとして `[10, 20]` で宣言するコードを書いてください。', hint: '配列と似ていますが、要素ごとの型と順番を固定できます。', answer: 'const point: [number, number] = [10, 20];', explanation: 'タプルは要素数と順序を固定したいときに使います。', common_mistakes: '`number[]` だと長さや順序までは縛れません。' }),
  ts({ id: 'local-typescript-007', theme_id: 'local-typescript-function', themeName: 'TypeScript: 関数型', title: '引数と戻り値が number の関数を書く', level: 1, type: 'code', statement: '`a` と `b` を受け取り、足し算結果を返す関数 `add` を TypeScript で書いてください。', hint: '引数と戻り値に number を付けます。', answer: 'function add(a: number, b: number): number {\n  return a + b;\n}', explanation: 'TypeScript では引数型と戻り値型を明示できます。', common_mistakes: '戻り値の `: number` を省くと推論はされますが、意図が見えにくくなります。' }),
  ts({ id: 'local-typescript-008', theme_id: 'local-typescript-function', themeName: 'TypeScript: 関数型', title: 'string を返すアロー関数を書く', level: 1, type: 'code', statement: '`name` を受け取り `Hello, ${name}` を返すアロー関数 `greet` を書いてください。', hint: '引数の型は string、戻り値も string です。', answer: 'const greet = (name: string): string => `Hello, ${name}`;', explanation: 'アロー関数でも引数型と戻り値型を書けます。', common_mistakes: 'テンプレートリテラル内の変数展開を忘れないことが大事です。' }),
  ts({ id: 'local-typescript-009', theme_id: 'local-typescript-function', themeName: 'TypeScript: 関数型', title: 'オプショナル引数を持つ関数を書く', level: 2, type: 'code', statement: '`name` は必須、`title` は省略可能な `buildLabel` 関数を書いてください。title があれば `${title} ${name}`、なければ `name` を返します。', hint: '省略可能引数は `?` を付けます。', answer: 'function buildLabel(name: string, title?: string): string {\n  return title ? `${title} ${name}` : name;\n}', explanation: '省略可能引数は `?` で表現できます。', common_mistakes: '必須引数より前に省略可能引数を置くと分かりにくくなります。' }),
  ts({ id: 'local-typescript-010', theme_id: 'local-typescript-function', themeName: 'TypeScript: 関数型', title: 'void 戻り値の関数を書く', level: 1, type: 'code', statement: '`message` を受け取り `console.log` する `logMessage` 関数を書いてください。戻り値はありません。', hint: '戻り値型は void です。', answer: 'function logMessage(message: string): void {\n  console.log(message);\n}', explanation: '返り値を使わない関数には `void` を付けます。', common_mistakes: '`return message;` を書くと意図とずれます。' }),
  ts({ id: 'local-typescript-011', theme_id: 'local-typescript-function', themeName: 'TypeScript: 関数型', title: 'コールバック型を持つ関数を書く', level: 2, type: 'code', statement: '`value: number` と `callback` を受け取り、`callback(value)` を実行する `runCallback` 関数を書いてください。callback の型も明示してください。', hint: '関数型は `(value: number) => void` の形です。', answer: 'function runCallback(value: number, callback: (value: number) => void): void {\n  callback(value);\n}', explanation: '関数を引数で受けるときも型を明示できます。', common_mistakes: 'callback を `Function` だけで済ませると型安全性が落ちます。' }),
  ts({ id: 'local-typescript-012', theme_id: 'local-typescript-function', themeName: 'TypeScript: 関数型', title: 'Promise を返す関数を書く', level: 2, type: 'code', statement: '文字列 `"ok"` を返す `async` 関数 `fetchStatus` を書いてください。戻り値型も明示してください。', hint: 'async 関数の戻り値は Promise になります。', answer: 'async function fetchStatus(): Promise<string> {\n  return "ok";\n}', explanation: '非同期関数では戻り値型を `Promise<型>` として書けます。', common_mistakes: '戻り値型を `string` にすると実際の async の挙動とずれます。' }),
  ts({ id: 'local-typescript-013', theme_id: 'local-typescript-object', themeName: 'TypeScript: オブジェクト型', title: 'User 型のオブジェクトを書く', level: 1, type: 'code', statement: '`id: number`, `name: string` を持つ `user` オブジェクトを型注釈つきで書いてください。値は `1` と `"Aoki"` にしてください。', hint: 'インラインのオブジェクト型で書けます。', answer: 'const user: { id: number; name: string } = {\n  id: 1,\n  name: "Aoki",\n};', explanation: 'オブジェクトにも型注釈を付けられます。', common_mistakes: 'プロパティ名のスペルがずれると型チェック以前に値参照で困ります。' }),
  ts({ id: 'local-typescript-014', theme_id: 'local-typescript-object', themeName: 'TypeScript: オブジェクト型', title: 'interface で Task を定義する', level: 1, type: 'code', statement: '`id: number`, `title: string`, `done: boolean` を持つ `Task` interface を書いてください。', hint: 'interface 名は Task です。', answer: 'interface Task {\n  id: number;\n  title: string;\n  done: boolean;\n}', explanation: '再利用したいオブジェクト形は interface で切り出すと見通しが良くなります。', common_mistakes: '型名を小文字で始めると識別しづらくなります。' }),
  ts({ id: 'local-typescript-015', theme_id: 'local-typescript-object', themeName: 'TypeScript: オブジェクト型', title: 'interface を使った Task オブジェクトを書く', level: 1, type: 'code', statement: '`Task` interface がある前提で、`id: 1`, `title: "Study"`, `done: false` の `task` を書いてください。', hint: '変数側に `: Task` を付けます。', answer: 'const task: Task = {\n  id: 1,\n  title: "Study",\n  done: false,\n};', explanation: '定義済み interface を使うと型の再利用ができます。', common_mistakes: 'done を文字列 `"false"` にすると型が合いません。' }),
  ts({ id: 'local-typescript-016', theme_id: 'local-typescript-object', themeName: 'TypeScript: オブジェクト型', title: 'readonly プロパティを持つ interface を書く', level: 2, type: 'code', statement: '`id` は readonly、`title` は通常の string とする `TaskSummary` interface を書いてください。', hint: '変更禁止にしたいプロパティの前に readonly を付けます。', answer: 'interface TaskSummary {\n  readonly id: number;\n  title: string;\n}', explanation: '外から変えてほしくない識別子に readonly を付けるのは実務でも有効です。', common_mistakes: '変わる値まで readonly にすると更新設計が不自然になることがあります。' }),
  ts({ id: 'local-typescript-017', theme_id: 'local-typescript-object', themeName: 'TypeScript: オブジェクト型', title: 'ネストしたオブジェクト型を書く', level: 2, type: 'code', statement: '`user` が `name: string` と `profile: { city: string }` を持つ型注釈つきオブジェクトを書いてください。値は `Aoki` と `Tokyo` にしてください。', hint: 'ネスト先にも型を付けます。', answer: 'const user: { name: string; profile: { city: string } } = {\n  name: "Aoki",\n  profile: {\n    city: "Tokyo",\n  },\n};', explanation: 'ネスト構造も型で明確にできます。', common_mistakes: 'profile を文字列にすると構造が崩れます。' }),
  ts({ id: 'local-typescript-018', theme_id: 'local-typescript-object', themeName: 'TypeScript: オブジェクト型', title: '型エイリアスで API レスポンスを定義する', level: 2, type: 'code', statement: '`success: boolean`, `message: string` を持つ `ApiResponse` 型エイリアスを書いてください。', hint: '`type` を使います。', answer: 'type ApiResponse = {\n  success: boolean;\n  message: string;\n};', explanation: 'オブジェクト形は interface だけでなく type alias でも表現できます。', common_mistakes: 'type 名は値ではなく型として使うことを意識します。' }),
  ts({ id: 'local-typescript-019', theme_id: 'local-typescript-generics', themeName: 'TypeScript: Generics', title: 'ジェネリック関数 identity を書く', level: 2, type: 'code', statement: '受け取った値をそのまま返すジェネリック関数 `identity` を書いてください。', hint: '`<T>` を使います。', answer: 'function identity<T>(value: T): T {\n  return value;\n}', explanation: 'ジェネリクスを使うと入力型と出力型の対応を保てます。', common_mistakes: '`any` にすると型情報が失われます。' }),
  ts({ id: 'local-typescript-020', theme_id: 'local-typescript-generics', themeName: 'TypeScript: Generics', title: '配列の先頭を返すジェネリック関数を書く', level: 2, type: 'code', statement: '`items` 配列を受け取り先頭要素を返すジェネリック関数 `firstItem` を書いてください。戻り値は `T | undefined` にしてください。', hint: '空配列もあるので undefined を考えます。', answer: 'function firstItem<T>(items: T[]): T | undefined {\n  return items[0];\n}', explanation: '配列要素型をジェネリクスで保つ基本問題です。', common_mistakes: '戻り値を常に T にすると空配列ケースを表せません。' }),
  ts({ id: 'local-typescript-021', theme_id: 'local-typescript-generics', themeName: 'TypeScript: Generics', title: 'ジェネリック interface Box を書く', level: 2, type: 'code', statement: '`value` という 1 プロパティを持つジェネリック interface `Box<T>` を書いてください。', hint: 'interface 名の後ろに `<T>` を付けます。', answer: 'interface Box<T> {\n  value: T;\n}', explanation: 'ジェネリック interface は再利用しやすい入れ物を作るのに便利です。', common_mistakes: 'value の型を any にするとジェネリクスの意味が薄れます。' }),
  ts({ id: 'local-typescript-022', theme_id: 'local-typescript-generics', themeName: 'TypeScript: Generics', title: 'Promise の中身型を明示する', level: 2, type: 'code', statement: 'ユーザー一覧を返す非同期関数の戻り値型として、`Task[]` を返す Promise 型を書いてください。', hint: 'Promise の山かっこ内に配列型を入れます。', answer: 'Promise<Task[]>', explanation: 'Promise の中身型まで明示すると利用側で扱いやすくなります。', common_mistakes: '`Task[]` だけだと非同期であることが表現されません。' }),
  ts({ id: 'local-typescript-023', theme_id: 'local-typescript-generics', themeName: 'TypeScript: Generics', title: 'keyof を使う関数シグネチャを書く', level: 3, type: 'code', statement: '`obj` と `key` を受け取り、`obj[key]` を返す `getValue` 関数シグネチャを書いてください。`key` は `obj` のキーに限定してください。', hint: '`K extends keyof T` を使います。', answer: 'function getValue<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}', explanation: 'keyof とジェネリクスを組み合わせると安全なキー参照ができます。', common_mistakes: 'key を string にしてしまうと存在しないキーも通ってしまいます。' }),
  ts({ id: 'local-typescript-024', theme_id: 'local-typescript-generics', themeName: 'TypeScript: Generics', title: 'ジェネリック型エイリアス ApiResult を書く', level: 3, type: 'code', statement: '`data: T` と `success: boolean` を持つジェネリック型エイリアス `ApiResult<T>` を書いてください。', hint: '`type ApiResult<T> = { ... }` の形です。', answer: 'type ApiResult<T> = {\n  data: T;\n  success: boolean;\n};', explanation: 'API レスポンスを汎用化すると複数画面で再利用しやすくなります。', common_mistakes: 'data を any にすると型情報が抜けます。' }),
  ts({ id: 'local-typescript-025', theme_id: 'local-typescript-practical', themeName: 'TypeScript: 実務型設計', title: 'CreateTaskRequest 型を書く', level: 3, type: 'code', statement: '`title: string` と `description: string` を持つ `CreateTaskRequest` 型エイリアスを書いてください。', hint: 'API 送信 DTO を意識します。', answer: 'type CreateTaskRequest = {\n  title: string;\n  description: string;\n};', explanation: 'リクエスト DTO を型で切ると API 呼び出し側の見通しが良くなります。', common_mistakes: '画面専用の状態まで混ぜると DTO の責務がぶれます。' }),
  ts({ id: 'local-typescript-026', theme_id: 'local-typescript-practical', themeName: 'TypeScript: 実務型設計', title: 'TaskStatus のリテラル型を書く', level: 3, type: 'code', statement: 'タスク状態を `"todo" | "doing" | "done"` で表す `TaskStatus` 型を書いてください。', hint: '文字列リテラルのユニオンです。', answer: 'type TaskStatus = "todo" | "doing" | "done";', explanation: '決まった状態だけを許すと UI と API のずれを減らせます。', common_mistakes: '`string` にすると制約が弱くなります。' }),
  ts({ id: 'local-typescript-027', theme_id: 'local-typescript-practical', themeName: 'TypeScript: 実務型設計', title: 'Task 型で status を TaskStatus にする', level: 3, type: 'code', statement: '`id: number`, `title: string`, `status: TaskStatus` を持つ `Task` interface を書いてください。', hint: 'status に先ほどの型を再利用します。', answer: 'interface Task {\n  id: number;\n  title: string;\n  status: TaskStatus;\n}', explanation: '状態型を切り出すと、他の DTO とも整合を取りやすくなります。', common_mistakes: 'status を string に戻すと型設計の意味が薄れます。' }),
  ts({ id: 'local-typescript-028', theme_id: 'local-typescript-practical', themeName: 'TypeScript: 実務型設計', title: 'Partial を使った更新型を書く', level: 3, type: 'code', statement: '`Task` の部分更新を表す `UpdateTaskPayload` 型エイリアスを書いてください。', hint: '標準ユーティリティ型を使います。', answer: 'type UpdateTaskPayload = Partial<Task>;', explanation: '更新 API で一部項目だけ送りたいときに便利です。', common_mistakes: '毎回すべてのプロパティを必須にすると部分更新と相性が悪くなります。' }),
  ts({ id: 'local-typescript-029', theme_id: 'local-typescript-practical', themeName: 'TypeScript: 実務型設計', title: 'Record を使ったエラーマップ型を書く', level: 3, type: 'code', statement: 'フォームエラーを `項目名 -> エラーメッセージ` で持つ `FormErrors` 型を `Record` で書いてください。キーも値も string です。', hint: '`Record<string, string>` の形です。', answer: 'type FormErrors = Record<string, string>;', explanation: 'キーと値のパターンが決まっている辞書構造は Record が便利です。', common_mistakes: '配列型にすると項目名で直接引けません。' }),
  ts({ id: 'local-typescript-030', theme_id: 'local-typescript-practical', themeName: 'TypeScript: 実務型設計', title: 'unknown を絞り込んで string 判定するコードを書く', level: 3, type: 'code', statement: '`value: unknown` を受け取り、string のときだけ `value.toUpperCase()` を返し、それ以外は `null` を返す関数を書いてください。', hint: '`typeof value === "string"` で絞り込みます。', answer: 'function toUpperIfString(value: unknown): string | null {\n  if (typeof value === "string") {\n    return value.toUpperCase();\n  }\n  return null;\n}', explanation: 'unknown はそのまま使えないので、型の絞り込みが必要です。', common_mistakes: 'any に逃げると型安全性がなくなります。' }),
]
